### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by lucasjaviluna** [FacuTaborra/FastServices#101]
[Middle]
	Hay mucha repetición de código al agregar los headers en las request al backend. Ej: https://vscode.dev/github/FacuTaborra/FastServices/blob/main/client/src/components/cliente/solicitud/Solicitud.jsx#L48
	Se podría utilizar algún interceptor de fetch para hacer esto de manera centralizada

**Comment by FacuTaborra** [comment]
A que se refiere con hacerlo de manera centralizada?

**Comment by FacuTaborra** [comment]
https://github.com/FacuTaborra/FastServices/pull/104
pull request donde mostramos la forma que utilizamos para centralizar los fetch. Los cambios nuevos seria en la carpeta client/services

**Comment by FacuTaborra** [comment]
Ya esta terminado
